name: Create New Branch Without Commit History

on:
  push:
    branches:
      - main

jobs:
  create-branch:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure git user
    - name: Configure git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Create a new orphan branch
    - name: Create orphan branch
      run: |
        git checkout --orphan new-branch # 创建没有历史记录的分支
        git rm -rf . # 删除当前工作目录中的所有文件

    # Checkout files from main branch and add them to the new branch
    - name: Checkout files from main branch
      run: |
        git checkout main -- . # 从main分支获取文件
        git add . # 添加所有文件到暂存区

    # Commit the changes
    - name: Commit changes
      run: |
        git commit -m "Add files from main branch to new-branch"
    
    # Push the new branch to remote repository
    - name: Push new branch
      run: |
        git push origin new-branch
